### ISSUE TITLE
To-Do List:

### ISSUE THREAD

**Issue by TheRiftGuardian** [TheRiftGuardian/itec4010_recipe_application#1]
# High Priority
- [x] Separate Recipe post body into two sections steps and instructions
- [x] Add additional attributes to recipe like rating
- [x] Add average rating to home page
- [x] Add search and sort functionality to home page

# Medium Priority
- [x] Resolve 404 login manager error when db is empty. Login manager get_or_404 has to be re-written.

# Low Priority
- [ ] Possible Forum implementation
- [ ] Possible Meal Prep implementation
- [ ] Additional Security features like email verification.
- [ ] Add User Profile for User recipes
- [ ] Favorite  recipe function

**Comment by TheRiftGuardian** [comment]
Resolved Login Manager error. Just had to delete a cookie that was saved. It attempted to access a user.id that didn't exist because the data from the database was wiped.

**Comment by TheRiftGuardian** [comment]
More issues done.
